subroutine input_data_GiD()


use variables
    implicit none

    integer :: ipoin, idime, nb_tab_dyn, ivfix, ifpre, iprop, ielem, igaus
    integer :: i, j, idofn, ifdof, imats, istep, ngash, nloca, numat, numel, inode
    integer :: icompt, itotv

!     real :: cond(mpoin,5)
    character (len=60) :: title
    character (len=60) :: atemp

    include 'subroutines/interface.f90'

    ! If you want to print console output in a txt file
    !   open(unit=6,file='output_terminal.txt')         !Writing of the variables values


    ! Create file to store element stiffness matrices
    open(unit=1,form='unformatted',file='temp/estif.tmp')


! *******************************************
! NAME OF THE .DAT FILE GENERATED BY GID
! *******************************************
open(5,file='PreProcessing/Triaxial.gid/Triaxial.dat')
! *******************************************

do i=1,16
    read(5,*)
end do

!Read main caracteristics of the geometry
read(5,*) atemp,npoin
read(5,*) atemp,nelem
read(5,*) atemp,nvfix
read(5,*) atemp,ntype
read(5,*) atemp,nnode
read(5,*) atemp,nmats
read(5,*) atemp,ngaus
read(5,*) atemp,nalgo
read(5,*) atemp,ncrit
read(5,*) atemp,nincs
read(5,*) atemp,nstre
read(5,*) atemp,ndim
read(5,*) atemp,epsilon
read(5,*) atemp,nstage

!For mechanical use, only 2 degrees of freedom per node: X and Y
ndofn=2

nevab=ndofn*nnode
    nstr1=nstre+1

    if(ntype == 3) then
        nstr1=nstre
    end if

    ntotv=npoin*ndofn
    ngaus2=ngaus*ngaus
    ntotg=nelem*ngaus2


        !Number of Degrees Of Freedom per Node. =2: X et Y
        mfron=ndofn*npoin       !Maximum front width

        mstif=(mfron*mfron-mfron)/2.0 +mfron



!Number of material parameters required to define characteristics of a material completely
!=4 for elasto-plastic problem; =2 for other applications; =11 for Cam Clay

if (ncrit<=4) then
    nprop=7
else if (ncrit==5) then
    nprop=11
else if (ncrit==6) then
    nprop=16
end if

!On est tranquille et on peut mélanger plusieurs matériaux avec différents criteres
! nprop=11
! nprop=16

    !  ***      DYNAMIC ALLOCATION OF MEMORY  ****
    include 'workspace/Alloc.f90'

    if (ncrit==5 .or. ncrit==6) then
        include 'workspace/Alloc_CamClay.f90'
    end if


        write(6,901) npoin,nelem,nvfix,ntype,nnode,nmats,ngaus,nevab,nalgo,ncrit,nincs,nstre !2
    901 format(//8h npoin =,i4,4x,8h nelem =,i4,4x,8h nvfix =,i4,4x,        &
                      8h ntype =,i4,4x,8h nnode =,i4,                       &
                      //8h nmats =,i4,4x,8h ngaus= ,i4,                     &
                      4x,8h nevab =,i4,4x,8h nalgo =,i4,4x,                 &
                      //8h ncrit =,i4,4x,8h nincs =,i4,4x,8h nstre =,i4)

 !call check1(ndofn,nelem,ngaus,nmats,nnode,npoin,nstre,ntype,nvfix,ncrit,nalgo,nincs)
    call check1( )

    ! On indique le type de problem:
    write(6,*) ''
    write(6,*) '--------------------------------------------'
    if (ntype==1) then
        write(6,*), "CALCUL CHARACTERISTICS: PLANE STRESS"
    end if

    if (ntype==2) then
        write(6,*) "CALCUL CHARACTERISTICS: PLANE STRAIN"
    end if

    if (ntype==3) then
        write(6,*) "CALCUL CHARACTERISTICS: AXISYMMETRIC PROBLEM"
    end if

    select case(ncrit)
        case(1)     !ncrit=1: Tresca yield criterion
            write(6,*) "TRESCA"

        case(2)     !ncrit=2: Von Mises
            write(6,*) "VON MISES"
    !
        case(3)     !ncrit=3: Mohr-Coulomb
            write(6,*) "MOHR-COULOMB"

        case(4)     !ncrit=4: Drucker-Prager
            write(6,*) "DRUCKER-PRAGER"

        case(5)     !ncrit=5: Cam-Clay
            write(6,*) "CAM CLAY"
    end select


    write(6,*) '--------------------------------------------'

do i=1,5
    read(5,*)
end do

!------------------------------------
!Read connectivity table
!------------------------------------

    !Read the elements nodal connections and the property numbers
        write(6,902) !3
    902 format(//8h element,3x,8hproperty,6x,12hnode numbers)

 903 format(1x,i5,i9,6x,8i5)
if (nnode==4) then
    do ielem=1,nelem
        read(5,*) numel,matno(numel),(lnods(numel,inode),inode=1,nnode)   !6
        write(6,903) numel,matno(numel),(lnods(numel,inode),inode=1,nnode)!4
    end do
end if

if (nnode==8) then
    do ielem=1,nelem
        read(5,*) numel,matno(numel),lnods(numel,1) ,lnods(numel,3) ,lnods(numel,5) ,lnods(numel,7) ,lnods(numel,2), &
            & lnods(numel,4),lnods(numel,6),lnods(numel,8)  !6
        write(6,903) numel,matno(numel),(lnods(numel,inode),inode=1,nnode)!4
    end do
end if

if (nnode==9) then
    do ielem=1,nelem
        read(5,*) numel,matno(numel),lnods(numel,1) ,lnods(numel,3) ,lnods(numel,5) ,lnods(numel,7) ,lnods(numel,2), &
            & lnods(numel,4),lnods(numel,6),lnods(numel,8),lnods(numel,9)    !6
        write(6,903) numel,matno(numel),(lnods(numel,inode),inode=1,nnode)!4
    end do
end if

!------------------------------------
! Read point coordinates
!------------------------------------
do i=1,5
    read(5,*)
end do

    ! Set to zero all the nodal coordinates, prior to reading some of them
    do ipoin=1,npoin
        do idime=1,ndim
            coord(ipoin,idime)=0.0
        end do
    end do



    ! Read some nodal coordinates, finishing with the last node of all
    ! Numeros des noeuds + coord. dans ficher de sortie
        write(6,904) !5
    904 format(//5h node,10x,1hx,10x,1hy)


    !7 Lecture des coordonnees
    do while (ipoin/=npoin)
        read(5,*) ipoin,(coord(ipoin,idime), idime=1,ndim) !7
        write(6,906) ipoin,(coord(ipoin,idime), idime=1,ndim) !6
    end do

    905 format(i5,6f10.5)

    ! interpolate coordinates of mid-side nodes
    !call nodexy(coord,lnods,melem,mpoin,nelem,nnode)

    if (nnode>3) then
        call nodexy( )
    end if


!     do ipoin=1,npoin
!         write(6,906) ipoin,(coord(ipoin,idime), idime=1,ndim) !6
!     end do

    906 format(1x,i5,3f10.4)

do i=1,5
    read(5,*)
end do
!------------------------------------
    !Read materials properties
!------------------------------------
! Properties are ordered as follows:
! 1 - Young E
! 2 - Poisson
! 3 - Thickness
! 4 - Density
! 5 - Yield stress pyI/sigma_y/etc...
! 6 - Hardening parameter H'
! 7 - Friction angle phi
! 8 - Nlambda, specific volume of NCL at 1 kPa
! 9 - lambda, slope of NCL
! 10 - kappa, slope of URL
! 11 - M, slope of CSL
! 12 - pyII, secondary yield stress where degradation occurs
! 13 - beta, rate of degradation
! 14 - Dei, additional void ratio at p'=pyI (yield)
! 15 - Dec, residual void ratio at p'->+inf
! 16 - p'b, tensile strength due to cohesion

  ! Read the available selection of element properties
    write(6,923)
    923  format( //20hMaterials properties)
    16  write(6,910)
    910  format(6hNumber,6x,19h Element properties)


        do imats=1,nmats
            read(5,*) numat,(props(numat,iprop),iprop=1,nprop) !10
    !     930 format(8f10.5)
            write(6,*) numat,(props(numat,iprop),iprop=1,nprop)
        end do


     ! Set up gaussian integration constants
        !call gaussq(ngaus,posgp,weigp)
    call gaussq( )






    return

end
